# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: DavidDarnes # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: David Darnes # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DavidDarnes
    - https://www.facebook.com/daviddarnes
    - https://www.linkedin.com/in/daviddarnes
    - https://plus.google.com/+DavidDarnes
    - https://github.com/daviddarnes

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: US/Eastern # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title:  # Needed for Siteleaf
    output: true
    description:  # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Chris Brennan | Designer" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/intro-pic.png" # Site logo, also used in jekyll-seo-tag
description: "Chris Brennan | Designer" # Site description and default description, also used in jekyll-seo-tag
url: "http://chrisbrennanpgh.com/" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/pizzapgh"
email: "chrisbrennanpgh@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://en.gravatar.com/userimage/95175156/73e259aa00c36886d67fc8353a0665d0" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by David Darnes: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
